name: Build Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    strategy:
      matrix:
        architecture: [x86_64]
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build with Nuitka
        run: |
          $VERSION = python -c "from app.common.setting import VERSION; print(VERSION)"
          Write-Host "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV
          python deploy.py

      - name: Download and extract tools
        shell: pwsh
        run: |
          # Setup variables
          $ZIP_URL = "https://github.com/zhiyiYo/Fluent-M3U8-Tools/releases/download/v0.1.0/Windows-${{ matrix.architecture }}.zip"
          $DEST_DIR = "dist/Fluent-M3U8.dist"

          # download zip
          Write-Output "Downloading package from $ZIP_URL..."
          Invoke-WebRequest -Uri $ZIP_URL -OutFile "$env:TEMP/package.zip"

          # unzip
          Write-Output "Extracting package..."
          Expand-Archive -Path "$env:TEMP/package.zip" -DestinationPath $DEST_DIR -Force

          # delete zip
          Remove-Item "$env:TEMP/package.zip" -Force

          Write-Output "Download and extraction complete!"

      - name: Download Inno Setup Translation Files
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl" -OutFile "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl"

      - name: Build Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: Fluent-M3U8.iss

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: Fluent-M3U8-v${{ env.VERSION }}-Windows-${{ matrix.architecture }}-Setup
          path: dist/Fluent-M3U8-v${{ env.VERSION }}-Windows-${{ matrix.architecture }}-Setup.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fluent-M3U8-v${{ env.VERSION }}-Windows-${{ matrix.architecture }}
          path: dist/Fluent-M3U8.dist

